### ISSUE TITLE
Crash on start-up (1.18.2, Forge)

### ISSUE THREAD

**Issue by Nevrai** [The-Acronym-Coders/ContentTweaker#261] opened 2022-08-02 21:35 UTC
**Crash report:** https://pastebin.com/raw/CV3ENbKE
**latest.log:** https://pastebin.com/raw/Fr0ZSBBZ

(`java.lang.RuntimeException: java.lang.reflect.InvocationTargetException`)

Tested on a fresh install, with no other mods.

### Mod list
* ContentTweaker-forge-1.18.2-1.0.0+7.jar
* CraftTweaker-forge-1.18.2-9.1.182.jar

### Versions
* **Minecraft:** 1.18.2
* **ContentTweaker:** 1.0.0+7 (latest)
* **CraftTweaker:** 9.1.182 (latest)
* **Forge:** 40.1.68 (latest)

**Comment by jaredlll08** [comment] 2022-08-02 22:51
Duplicate of https://github.com/CraftTweaker/ContentTweaker/issues/260

**Closed as not planned by jaredlll08** 2022-08-02 22:51 UTC

**Comment by Nevrai** [comment] 2022-08-02 22:54
> Duplicate of #260

I saw #260, but it didn’t seem like it was the same cause. Maybe I’m wrong, though. If so, apologies for the duplicate.
