### ISSUE TITLE
Trying to diagnose an unrelated crash, ran into this

### ISSUE THREAD

**Issue by Sunconure11** [The-Acronym-Coders/ContentTweaker#161] opened 2018-12-29 04:05 UTC
https://paste.dimdev.org/esisanokoy.mccrash

**Comment by SkySom** [comment] 2018-12-29 09:26
Submitting an issue multiple times does not make it more likely to be fixed. Duplicate of #138 and #150

**Closed as completed** 2018-12-29 09:34 UTC

**Comment by Sunconure11** [comment] 2018-12-29 22:16
Wait, WTF? I submitted this fairly late, didn't realize it was the same error as before. And yet I haven't touched my scripts.

**Comment by SkySom** [comment] 2018-12-29 22:18
There's something up with your lang file such that it isn't loading right. No idea yet.
